name: Restrict PRs to main
on:
  pull_request:
    branches:
      - main
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Only pull requests from 'dev' branch can be merged into 'main'."
            exit 1
          fi
